[package]
name = "cligpt"
version = "0.1.0"
edition = "2021"
authors = ["Felipe S. S. Schneider <schneider.felipe.5@gmail.com>"]
description = "A command-line interface for ChatGPT"
rust-version = "1.64.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = "0.10.1"
clap = { version = "4.1.13", features = ["derive", "env"] }
futures-util = "0.3.27"
tokio = { version = "1.26.0", features = ["rt-multi-thread"] }
